/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.78
 * Generated at: 2022-06-10 14:47:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<!-- \r\n");
      out.write("		*프레임 워크\r\n");
      out.write("		-개발자가 보다 편리한 환경에서 개발을 할 수 있도록 제공하는 틀\r\n");
      out.write("		-소프트웨어 개발의 입장에서 봤을땐 공통으로 사용하는 라이브러리 / 개발도구 / 인터페이스 등등을 의미한다\r\n");
      out.write("		\r\n");
      out.write("		*프레임 워크를 왜 사용하는가 ? \r\n");
      out.write("		-현재 웹프로그래밍 규모가 커지고 있고 그에따라 프로젝트가 복잡도가 증가하고 규모가 커지기 때문에\r\n");
      out.write("		-보다 높은 완성도를 위해 많은 사람들을 필요로 하고 그 인원들이 통일성과 개발속도,안정성을 위해 사용하며\r\n");
      out.write("		-좋은 성과를 내고 있음.\r\n");
      out.write("		-요약하자면 생산성이 높다.\r\n");
      out.write("		\r\n");
      out.write("		*특징\r\n");
      out.write("		-개발자의 입맛대로 자유롭게 코딩하는것이 아니라 프레임워크에서 제공하고있는 가이드라인에 맞춰 개발한다.\r\n");
      out.write("		-개발 범위가 정해져 있다.\r\n");
      out.write("		-다양한 도구를 지원한다.\r\n");
      out.write("		\r\n");
      out.write("		*장단점\r\n");
      out.write("		-장점 : 개발시간을 줄일 수 있음.\r\n");
      out.write("		\r\n");
      out.write("		-단점 : 지나치게 의존하면 개발자 스스로의 능력저하가 있을 수 있음.\r\n");
      out.write("		\r\n");
      out.write("		*프레임워크의 종류 \r\n");
      out.write("		-영속성 : 데이터 관련한(CRUD) 기능들을 편리하게 작업할 수 있는 프레임워크\r\n");
      out.write("		-자바 : 웹 애플리케이션에 초점을 맞춰서 필요한 요소들을 모듈화해서 제공해주는 프레임워크\r\n");
      out.write("		-화면구현 : Front-end 개발을 보다 쉽게 구현할 수 있게 틀을 제공해주는 프레임워크\r\n");
      out.write("		-기능 및 지원 : 특정 기능 수행에 도움을 주는 기능을 제공하는 프레임워크\r\n");
      out.write("	 -->\r\n");
      out.write("\r\n");
      out.write("	<h1>어서와 마이바티스는 처음이지?</h1>\r\n");
      out.write("	\r\n");
      out.write("	<!-- index페이지가 로딩되자마자 WEB-INF/views/main.jsp로 포워딩된다. -->\r\n");
      out.write("	");
      if (true) {
        _jspx_page_context.forward("WEB-INF/views/main.jsp");
        return;
      }
      out.write("\r\n");
      out.write("	<!-- WEB-INF 폴더는 WAS가 관리하기때문에 직접 요청이 불가능하고 forward 처리를 통해서 접근 가능하다. -->\r\n");
      out.write("	\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
